# 텐서플로우
- 1.그래프 만들기
- 2.그래프 실행

In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant('Hello World')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [14]:
sess = tf.Session()

sess.run(hello)

b'Hello World'

3 : 스칼라 </br>

[] : 벡터 </br>

[[],[]] : 행렬 </br>

In [15]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)

sess.run(c)

42

### 플레이스 홀더
```
tf.placeholder(tf.float32,[None,3])
```
- 그래프에 사용할 입력값을 나중에 받는 매개변수

### 변수
```
tf.Variable(tf.random_normal([3,2]))
```
- 변하는 숫자

In [9]:
X = tf.placeholder(tf.float32,[None,3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [18]:
import tensorflow as tf

X = tf.placeholder(tf.float32,[None,3])

x_data = [[1,2,3],[4,5,6]]
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

expr = tf.matmul(X,W) + b

sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("====== W ======")
print(sess.run(W))
print("====== b ======")
print(sess.run(b))
print("==== expr ====")

print(sess.run(expr,feed_dict={X:x_data}))
sess.close()


=== x_data ===
[[1, 2, 3], [4, 5, 6]]
====== W ======
[[ 0.77293724 -0.96338135]
 [ 0.64620286  0.45558184]
 [ 0.01700941  0.10060246]]
====== b ======
[[0.22644597]
 [1.6398138 ]]
==== expr ====
[[2.342817   0.47603568]
 [8.064633   0.6678124 ]]


## Linear regression
- 선형회귀

In [6]:
import tensorflow as tf

x_data = [1,2,3]
y_data = [1,2,3]

W = tf.Variable(tf.random_uniform([1],-1.0,1.0)) # -1 ~ 1 사이에 균등분포
b = tf.Variable(tf.random_uniform([1],-1.0,1.0))

X = tf.placeholder(tf.float32,name='X')
Y = tf.placeholder(tf.float32,name='Y')

hypothesis = W*X + b # X와 Y의 관계

cost = tf.reduce_mean(tf.square(hypothesis - Y)) # 예측값 - 실제값 -> 제곱 -> 평균

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10):
        _, cost_val = sess.run([train,cost], feed_dict={X:x_data,Y:y_data})
        print(step,cost_val,sess.run(W),sess.run(b))
        
    print("\n=====test=====")
    print("X:5,Y:",sess.run(hypothesis,feed_dict={X:5}))
    print("X:2.5,Y:",sess.run(hypothesis,feed_dict={X:2.5}))

0 3.8332806 [0.7747356] [0.7355484]
1 0.11506554 [0.690763] [0.67854446]
2 0.067360155 [0.7079664] [0.6665304]
3 0.063655905 [0.7139189] [0.6500377]
4 0.060626198 [0.7209128] [0.6344626]
5 0.057746347 [0.72760916] [0.61920494]
6 0.055003345 [0.73415864] [0.6043203]
7 0.05239062 [0.7405491] [0.5897928]
8 0.04990204 [0.7467862] [0.57561463]
9 0.04753165 [0.7528732] [0.56177723]

=====test=====
X:5,Y: [4.3261433]
X:2.5,Y: [2.4439602]
