In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [7]:
raw_data = 'First Citizen'
n_samples = len(raw_data)
unique_chars = list(set(raw_data))
print(n_samples)
print(unique_chars)

13
['C', 'r', 'e', 'z', 'i', 't', 'n', ' ', 'F', 's']


In [8]:
# 문자를 정수로 변환하는 딕셔너리
char_to_int = { ch:i for i,ch in enumerate(unique_chars) }
# 정수를 문자로 변환하는 딕셔너리
int_to_char = { i:ch for i,ch in enumerate(unique_chars) }

print(char_to_int)
print(int_to_char)

{'s': 9, 'C': 0, 'r': 1, 'e': 2, 'z': 3, 'i': 4, 't': 5, 'F': 8, ' ': 7, 'n': 6}
{0: 'C', 1: 'r', 2: 'e', 3: 'z', 4: 'i', 5: 't', 6: 'n', 7: ' ', 8: 'F', 9: 's'}


In [11]:
n_unique_chars = len(unique_chars)
input_dim = n_unique_chars
num_classes = n_unique_chars

print('number of unique chars : ',n_unique_chars)

number of unique chars :  10


In [12]:
seq_len = n_samples-1

In [13]:
#-------------------------------------------
# 매개변수 설정
#-------------------------------------------
# 미니배치 크기: 1
# 은닉층 크기: 16
# 학습률: 0.1
# 반복 수: 20
batch_size = 1
hidden_size = 16
learning_rate = 0.1
n_epochs = 20

In [16]:
x = raw_data[:-1]
print('input : ',x)
y = raw_data[1:]
print('output : ',y)

input :  First Citize
output :  irst Citizen


In [17]:
x_int = [char_to_int[n] for n in x]
print('input : ',x_int)
y_int = [char_to_int[n] for n in y]
print('output : ',y_int)

input :  [8, 4, 1, 9, 5, 7, 0, 4, 5, 4, 3, 2]
output :  [4, 1, 9, 5, 7, 0, 4, 5, 4, 3, 2, 6]


In [20]:
x_one_hot = tf.keras.utils.to_categorical(x_int, 
n_unique_chars).reshape(batch_size,seq_len, input_dim)

print('ont hot input : ',x_one_hot)

ont hot input :  [[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]]


In [31]:
model = tf.keras.models.Sequential([
    tf.keras.layers.SimpleRNN(hidden_size,
                                  input_shape=[seq_len,input_dim],
                                  return_sequences=True)
])

model.compile(optimizer='adam',
              learning_rate=learning_rate,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [34]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 12, 16)            432       
Total params: 432
Trainable params: 432
Non-trainable params: 0
_________________________________________________________________
