In [3]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [4]:
raw_data = 'First Citizen'
n_samples = len(raw_data)
unique_chars = list(set(raw_data))
print(n_samples)
print(unique_chars)

13
['s', 'r', 'F', ' ', 't', 'C', 'n', 'e', 'z', 'i']


In [5]:
# 문자를 정수로 변환하는 딕셔너리
char_to_int = { ch:i for i,ch in enumerate(unique_chars) }
# 정수를 문자로 변환하는 딕셔너리
int_to_char = { i:ch for i,ch in enumerate(unique_chars) }

print(char_to_int)
print(int_to_char)

{'s': 0, 'n': 6, 'r': 1, 'e': 7, 'F': 2, ' ': 3, 't': 4, 'z': 8, 'i': 9, 'C': 5}
{0: 's', 1: 'r', 2: 'F', 3: ' ', 4: 't', 5: 'C', 6: 'n', 7: 'e', 8: 'z', 9: 'i'}


In [6]:
n_unique_chars = len(unique_chars)
input_dim = n_unique_chars
num_classes = n_unique_chars

print('number of unique chars : ',n_unique_chars)

number of unique chars :  10


In [7]:
seq_len = n_samples-1

In [36]:
#-------------------------------------------
# 매개변수 설정
#-------------------------------------------
# 미니배치 크기: 1
# 은닉층 크기: 16
# 학습률: 0.1
# 반복 수: 20
batch_size = 1
hidden_size = 16
learning_rate = 0.1
n_epochs = 100

In [37]:
x = raw_data[:-1]
print('input : ',x)
y = raw_data[1:]
print('output : ',y)

input :  First Citize
output :  irst Citizen


In [38]:
x_int = [char_to_int[n] for n in x]
print('input : ',x_int)
y_int = [char_to_int[n] for n in y]
print('output : ',y_int)

input :  [2, 9, 1, 0, 4, 3, 5, 9, 4, 9, 8, 7]
output :  [9, 1, 0, 4, 3, 5, 9, 4, 9, 8, 7, 6]


In [47]:
x_one_hot = tf.keras.utils.to_categorical(x_int, 
n_unique_chars).reshape(batch_size,seq_len, input_dim)

y_one_hot = tf.keras.utils.to_categorical(y_int, 
n_unique_chars).reshape(batch_size,seq_len, input_dim)

print('one hot input : ',x_one_hot)

one hot input :  [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]]


In [40]:
model = tf.keras.models.Sequential([
    tf.keras.layers.SimpleRNN(hidden_size,
                                  input_shape=[seq_len,input_dim],
                                  return_sequences=True),
    tf.keras.layers.Dense(num_classes)
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [41]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_6 (SimpleRNN)     (None, 12, 16)            432       
_________________________________________________________________
dense_1 (Dense)              (None, 12, 10)            170       
Total params: 602
Trainable params: 602
Non-trainable params: 0
_________________________________________________________________


In [42]:
y_int

[9, 1, 0, 4, 3, 5, 9, 4, 9, 8, 7, 6]

In [43]:
x_one_hot.shape

(1, 12, 10)

In [46]:
model.fit(np.array(x_one_hot), np.array(y_one_hot), epochs=n_epochs)

Train on 1 samples
Epoch 1/100
1/1 [==============================] - 0s 17ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 2/100
1/1 [==============================] - 0s 9ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 3/100
1/1 [==============================] - 0s 9ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 4/100
1/1 [==============================] - 0s 19ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 5/100
1/1 [==============================] - 0s 9ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 6/100
1/1 [==============================] - 0s 10ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 7/100
1/1 [==============================] - 0s 9ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 8/100
1/1 [==============================] - 0s 7ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 9/100
1/1 [==============================] - 0s 7ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 10/100
1/1 [==============================] - 0s 8ms/sample - loss: 12.0

Epoch 82/100
1/1 [==============================] - 0s 6ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 83/100
1/1 [==============================] - 0s 7ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 84/100
1/1 [==============================] - 0s 7ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 85/100
1/1 [==============================] - 0s 12ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 86/100
1/1 [==============================] - 0s 7ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 87/100
1/1 [==============================] - 0s 6ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 88/100
1/1 [==============================] - 0s 7ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 89/100
1/1 [==============================] - 0s 11ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 90/100
1/1 [==============================] - 0s 9ms/sample - loss: 12.0886 - accuracy: 0.0833
Epoch 91/100
1/1 [==============================] - 0s 11ms/sample - loss: 12.0886 - accu